name: Deploy Docker Image

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Get current date and time
      run: echo "CURRENT_DATE_TIME=$(date +'%d/%m/%Y_%H:%M:%S')" >> $GITHUB_ENV
  
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        tags: |
          104762879464.dkr.ecr.us-east-1.amazonaws.com/node-js-sample:latest
          104762879464.dkr.ecr.us-east-1.amazonaws.com/node-js-sample:${{ env.CURRENT_DATE_TIME }}

    - name: Push Docker image to ECR
      uses: aws-actions/amazon-ecr-push-action@v1
      with:
        region: ${{ env.AWS_REGION }}
        registry-url: 104762879464.dkr.ecr.us-east-1.amazonaws.com
        repository-name: node-js-sample
        tags: |
          latest
          ${{ env.CURRENT_DATE_TIME }}
